encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/", views.search_view),
    path("wiki/<str:entry_title>", views.entry, name="entry"),
    path("add/", views.add, name="add"),
    path("edit/<str:entry_title>", views.edit, name="edit"),
    path("random", views.random, name="random")
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponseRedirect
import re
from random import randint
from markdown2 import markdown

from . import util

class NewEntryForm(forms.Form):
    entry_title = forms.CharField(label="Title")
    entry_text = forms.CharField(label="Description")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry_title):
    entry_text = str(util.get_entry(entry_title.strip()))
    entry_text = markdown(entry_text)
    entry_list = util.list_entries()
    if entry_title in entry_list:
        return render(request, "encyclopedia/entry.html", {
            "entry_title": entry_title, "entry_text": entry_text
        })
    else:
        entry_text = "Error: Entry does not exist"
        return render(request, "encyclopedia/entry.html", {
            "entry_title": entry_title, "entry_text": entry_text
        })
    
def search_view(request):
    query_dict = request.GET #this is a dictionary
    query = query_dict.get("q") 
    search_results = []
    for entry in util.list_entries():
        if query.casefold() == entry.casefold():
            return HttpResponseRedirect(str(entry))
        
        if query.casefold() in entry.casefold():
            search_results.append(entry)
    
    return render(request, "encyclopedia/search.html", {
        "search_results":search_results, "query":query
    })
    
def add(request):
    if request.method == "POST":
        entry_title = request.POST.get("entry_title").strip()
        entry_text = request.POST.get("entry_text").strip()
        
        if entry_title == "" or entry_text == "":
            return render(request, "encyclopedia/add.html", {"message": "Please fill in all fields", "entry_title":entry_title, "entry_text":entry_text})
        
        if entry_title in util.list_entries():
            return render(request, "encyclopedia/add.html", {"message": "Error. Entry already exists.", "entry_title":entry_title, "entry_text":entry_text})
        
        entry_text = "<h1>"+str(entry_title)+"</h1>"+entry_text
        util.save_entry(entry_title, entry_text)
        return redirect("encyclopedia:entry", entry_title)
    
    return render(request, "encyclopedia/add.html")

def edit(request, entry_title):
    entry_text = util.get_entry(entry_title.strip())
    if entry_text == None:
        return render(request, "encyclopedia/edit.html", {'error':"404 Not Found"})
    if request.method == "POST":
        entry_text = request.POST.get("entry_text").strip()
        if entry_text == "":
            return render(request, "encyclopedia/edit.html", {"message": "Empty description", "entry_title":entry_title, "entry_text":entry_text})
        util.save_entry(entry_title, entry_text)
        return redirect("encyclopedia:entry", entry_title = entry_title)    
    return render(request, "encyclopedia/edit.html", {"entry_title": entry_title, "entry_text": entry_text})        
           
def random(request):
     entry_list = util.list_entries()
     random_entry = entry_list[randint(0, len(entry_list)-1)]
     return redirect("encyclopedia:entry", entry_title=random_entry)
            

    
    


    
    
            

            

    

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Entry Form</h1>
    {% if message %}
    <div class="alert alert-danger" style="text-align: center" role="alert">
        {{ message }}
    </div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <label for="entry_title">Entry Title:</label>
        <br>
        <input type="text" id="entry_title" name="entry_title">
        <br>
        <label for="entry_text">Description:</label>
        <br>
        <textarea class="form-control" id="entry_text" name="entry_text" cols="20" rows = "20" placeholder="Write page content in markdown"></textarea>
        <br>
        <br>
        <input type="submit" value="Save Entry">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}
    <h1>Edit Entry: {{ entry_title }}</h1>
    {% if error %}
    <h2 align="center">404 Not found</h2>
    {%else%}
    {% if message %}
    <div class="alert alert-danger" style="text-align: center" role="alert">
        {{ message }}
    </div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <label for="entry_title">Entry Title:</label>
        <br>
        <input type="text" id="entry_title" name="entry_title" value="{{ entry_title }}">
        <br>
        <br>
        <label for="entry_text">Description:</label>
        <br>
        <textarea class="form-control" id="entry_text" name="entry_text" cols="20" rows = "20" placeholder="Write description in markdown">
            {% if entry_text%}
            {{ entry_text | safe }}
            {% endif %}
        </textarea>
        <br>
        <br>
        <input type="submit" value="Update Entry">
    </form>
{% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }}
{% endblock %}

{% block body %}
    <a href="{% url 'encyclopedia:edit' entry_title %}">Edit This Page</a>
    <br>
    {{ entry_text | safe }}
    
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <a href="wiki/{{ entry }}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/wiki/" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>You searched for: {{ query }}</h1>

    <ul>
        {% for result in search_results %}
            <li><a href="{{ result }}">{{result}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}